title: Gary Coffey # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Fill in description
  <br><br>
  
  
theme: jekyll-theme-hacker
google_analytics: UA-166811677-1 # your Google Analytics tracking ID here
